version: '3.1'

services:
  web:
    build: frontend
    command: yarn start
    restart: always
    ports:
      - 3100:3000
    volumes:
      - ./frontend:/home/web
    networks:
      - api

  api:
    build: ./api
    command: yarn dev
    restart: always
    ports:
      - 5000:3000
    volumes:
      - ./api:/home/app
    networks:
      - shortener
      - api

  mongo:
    image: mongo
    restart: always
    networks:
      - shortener


networks:
  shortener:
  api:
