version: '3.1'

services:
  api:
    build: .
    command: yarn dev
    restart: always
    ports:
      - 5000:3000
    volumes:
      - .:/home/app
    networks:
      - shortener

  mongo:
    image: mongo
    restart: always
    networks:
      - shortener

networks:
  shortener:
